import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import LayoutComponent from '@/commons/layout/02-02';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 1) 02-02-layout-header-global 에서 사용한 레이아웃 */}
        <LayoutComponent>{children}</LayoutComponent>
      </body>
    </html>
  );
}
